name: flutter_fullpdfview
description: A new Flutter project.
version: 1.0.5
homepage: https://github.com/DudasMiklos/flutter_fullpdfview

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.github.DudasMiklos.flutter_fullpdfview
        pluginClass: FlutterFullpdfviewPlugin
      ios:
        pluginClass: FlutterFullpdfviewPlugin

# flutter:
#   plugin:
#     androidPackage: com.github.DudasMiklos.flutter_fullpdfview
#     pluginClass: FlutterFullpdfviewPlugin

# flutter:
#   plugin:
#     platforms:
#       ios:
#         pluginClass: FlutterFullpdfviewPlugin
#       android:
#         package: com.github.DudasMiklos.flutter_fullpdfview
#         pluginClass: FlutterFullpdfviewPlugin
    